excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://thunderswole.github.io
title: Awesome
email: 
author: thunderswole
description: My awesome new site
paginate: 3
google_analytics: 